language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master
script:
  - hexo generate
deploy:
  provider: pages
  token: $GH_TOKEN
  keep_history: true
  target_branch: deploy
  on:
    branch: master
  local_dir: public
