language: node_js
node_js:
- 12
cache: npm
branches:
  only:
  - master
install:
- npm install hexo-cli gulp-cli -g
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: public
  on:
    branch: master
addons:
  ssh_known_hosts:
  - "$IP"
before_install:
- openssl aes-256-cbc -K $encrypted_529cc86b1780_key -iv $encrypted_529cc86b1780_iv
  -in id_rsa_aws.enc -out ~/.ssh/id_rsa_aws -d
- chmod 600 ~/.ssh/id_rsa_aws
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- chmod 600 ~/.ssh/id_rsa_aws
- rsync -e "ssh -i ~/.ssh/id_rsa_aws" -az --delete ./public/* ubuntu@$IP:/home/ubuntu/github
- rsync -e "ssh -i ~/.ssh/id_rsa_aws" -az --delete ./public/* ubuntu@$IP:/usr/share/nginx/html/blog
