language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master
install:
  - npm install hexo-cli gulp-cli -g
  - npm install
addons:
  ssh_known_hosts: 45.76.160.45:22
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  on:
    branch: master
