language: node_js
node_js:
- 12
cache: npm
branches:
  only:
  - master
install:
- npm install hexo-cli gulp-cli -g
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - "$IP"
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- chmod 600 ~/.ssh/id_rsa
- rsync -e "ssh -i ~/.ssh/id_rsa" -az --delete ./public/* root@$IP:/root/html/blog
