language: node_js
node_js:
- 12
cache: npm
branches:
  only:
  - master
install:
- npm install hexo-cli gulp-cli -g
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: public
  on:
    branch: master
addons:
  ssh_known_hosts:
  - $IP
before_install:
- openssl aes-256-cbc -K $encrypted_edf35525f8fd_key -iv $encrypted_edf35525f8fd_iv
  -in id_rsa_aws.enc -out ~/.ssh/id_rsa_aws -d
- chmod 600 ~/.ssh/id_rsa_aws
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

# 执行部署脚本，将编译后的项目同步到服务器的nginx项目目录下
after_success:
  - chmod 600 ~/.ssh/id_rsa_aws
  - rsync -az --delete ./public/* ubuntu@$IP:/home/ubuntu/github
  - rsync -az --delete ./public/* ubuntu@$IP:/usr/share/nginx/html/blog

