sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master
script:
  - hexo generate && hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: deploy #部署到master分支
  on:
    branch: master
  local-dir: public
