version: '2.3'

services:
  mariadb:
    restart: always
    image: mariadb:10.2
    ports:
    - "33060:3306"
    volumes:
    - /home/mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=virola_mariadb_321
    - MYSQL_ROOT_HOST=%
    - MYSQL_DATABASE=trojan

  trojan:
    restart: always
    image: jrohy/trojan
    depends_on:
    - mariadb
    links:
    - mariadb
    ports:
    - "8080:80"
    - "4433:443"
    volumes:
    - /root/ssl:/root/ssl:Z
    environment:
    - DEBUG=false

# volumes:
#   redis-data:
#   postgresql-data:
#   gitlab-data: