name: deploy_vps
on:
  # 手动触发
  workflow_dispatch:
  # nothing
  push:
    branches: [master]

jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: v14.17.0

      #缓存依赖
      - name: Cache nodemodules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # 需要缓存的文件的路径
          path: ./node_modules
          # 对缓存的文件指定的唯一标识
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
          # 用于没有再找目标key的缓存的backup选项
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 装依赖
      - name: Install
        run: yarn global add hexo-cli && yarn

      # 打包
      - name: Build
        run: yarn build

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USER_NAME }}
          server: ${{ secrets.SERVER_HOST }}
          ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          local_path: './public/*'
          remote_path: '/root/html/blog'
          sftpArgs: '-o ConnectTimeout=5'
